#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

display_subdomain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  display_subdomain_info "$1" "www"
  display_subdomain_info "$1" "lb-01"
  display_subdomain_info "$1" "web-01"
  display_subdomain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  display_subdomain_info "$1" "$2"
fi
