#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Create a new Nginx configuration file for the custom 404 page
cat > /etc/nginx/sites-available/custom_404 <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
