#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend globalprogressions.tech_backend

backend globalprogressions.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 356893-web-01 100.25.17.119:80 check
    server 356893-web-02 54.88.101.99:80 check
EOT

sudo service haproxy restart
