#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

# Check if an argument is provided
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
exit 1
fi

# Extract the IP address from the command line argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 "$ip_address"
