#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
#+	by removing the symbolic link to the default configuration 
#+	file from the sites-enabled directory and creates a new symbolic
#+	link to the default configuration file in the sites-available 
#+	directory in the sites-enabled directory then restarts nginxs server
#+	to apply configuration settings

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
