#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.

# Infinite loop displaying the message with a sleep of 2 seconds
while true; do
    echo "To infinity and beyond"
    sleep 2
done
