#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash.

for file in *; do
    # Check if the file is not hidden
    if [[ ! $file == .* ]]; then
        # Extract the part of the name after the first dash
        display_name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$display_name"
    fi
done
