#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

# Use ifconfig to display active IPv4 IPs
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | grep -v '127.0.0.1' | grep -v '0.0.0.0'
